---
title: "Innovation_SEasia_2"
author: "Kazunori_Kasahara"
date: "2018/10/20"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}

```


```{r}
panel_RD <- read.csv('panel_data_by_label.csv')
panel_RD <- panel_RD %>% filter(is.na(panel_RD$Year) == FALSE)
panel_RD <- panel_RD %>% select(-1)
names(panel_RD)[1] <- 'country'
panel_RD$country<-c(rep('CHN',length(unique(panel_RD$Year))),rep('IDN',length(unique(panel_RD$Year))),rep('KOR',length(unique(panel_RD$Year))),rep('MYS',length(unique(panel_RD$Year))),rep('THA',length(unique(panel_RD$Year))))

panel_RD <- panel_RD %>% select(1,2,3,5,17,25)
names(panel_RD)[3:6] <- c('attitude_globalization','business_RD','IPR','total_RD')
panel_RD$total_RD <- as.numeric(as.character(panel_RD$total_RD))
panel_RD$business_RD <- as.numeric(as.character(panel_RD$business_RD))
panel_RD$public_RD <- panel_RD$total_RD - panel_RD$business_RD
names(panel_RD)[2] <- 'year'

education <- read_csv('year of education.csv')
education <- education[2:121,]
education <- education %>% select(-7,-8)
education <- education %>% select(2,3,6)
names(education) <- c ('country','year','edu_year') 

education$country<-c(rep('CHN',length(unique(education$year))),rep('IDN',length(unique(education$year))),rep('KOR',length(unique(education$year))),rep('MYS',length(unique(education$year))),rep('THA',length(unique(education$year))))
education$year <- as.numeric(education$year)


patent <- read.csv('patent.csv',skip = 7)
patent <- patent %>% select(1,2,3)
names(patent) <- c('country','year','patent')
patent$country <- as.character(patent$country)
patent$country[which(patent$country=='IND')] <-'IDN'

GDPperCapita <- read.csv('GDPperCapita.csv')
names(GDPperCapita) <- c('country','year','GDPpercapita')
GDPperCapita$country <- as.character(GDPperCapita$country)

panel_2 <- panel_RD %>% 
  left_join(GDPperCapita,by = c('country','year')) %>%
              left_join(patent,by = c('country','year')) %>%
              left_join(education,by = c('country','year'))

```


```{r}
panel_2$l_bus <- log(panel_2$business_RD)
panel_2$l_pub <- log(panel_2$public_RD)
panel_2$l_patent <- log(panel_2$patent)

```

```{r}
library(plm)
panel_2_panel <- pdata.frame(panel_2,c('country','year'))
panel_2_panel$attitude_globalization <- as.numeric(as.character(panel_2_panel$attitude_globalization))

equation1 <- l_patent ~ attitude_globalization + l_bus + l_pub + IPR + GDPpercapita + edu_year
model_fixed <- plm(equation1,data = panel_2_panel,model = "within")
summary(model_fixed)

```

```{r}
equation2 <- l_patent ~ attitude_globalization + l_bus + IPR + GDPpercapita + edu_year
model_fixed_2 <- plm(equation2,data = panel_2_panel,model = "within")
summary(model_fixed_2)
```



```{r}
ggplot(panel_2) + geom_line(aes(year,l_patent,col = country)) 
```





```{r}
ggplot(panel_2) + geom_line(aes(year,IPR,col = country))
```

```{r}
ggplot(panel_2) + geom_line(aes(year,l_bus,col = country))
```

```{r}
ggplot(panel_2) + geom_line(aes(year,l_pub,col = country))
```

```{r}
ggplot(panel_2) + geom_line(aes(year,edu_year,col = country))
```

```{r}
ggplot(panel_2) + geom_line(aes(year,GDPpercapita,col = country))
```
```{r}
plot(panel_2$l_pub,panel_2$l_bus)
```




